# Generated by go2rpm 1
%bcond_without check

# https://github.com/infrawatch/apputils
%global gohost          github
%global gosuffix        com
%global goorg           infrawatch
%global goproject       apputils
%global goipath         %{gohost}.%{gosuffix}/%{goorg}/%{goproject}
%global commit          46ad44e45f12c6b473f4eb0e0634f977b6d9f495
%global shortcommit     %(c=%{commit}; echo ${c:0:7})

%gometa

%global common_description %{expand:
Shared library for infrawatch golang components.}

%global godocs          README.md

Name:           golang-%{gohost}-%{goorg}-%{goproject}
Version:        0
Release:        0.1%{?dist}
Summary:        Shared library for infrawatch golang components

License:        # FIXME

URL:            %{gourl}
Source0:        https://%{goipath}/archive/%{commit}/%{goproject}-%{shortcommit}.tar.gz

BuildRequires:  golang(github.com/go-ini/ini)
BuildRequires:  golang(github.com/streadway/amqp)
BuildRequires:  golang(qpid.apache.org/amqp)
BuildRequires:  golang(qpid.apache.org/electron)
BuildRequires:  golang(github.com/stretchr/testify/assert)

Requires:  golang(github.com/go-ini/ini)
Requires:  golang(github.com/streadway/amqp)
Requires:  golang(qpid.apache.org/amqp)
Requires:  golang(qpid.apache.org/electron)

Provides:       golang(%{goipath})

%description
%{common_description}

%gopkg

%prep
%autosetup -n %{goproject}-%{commit}

%install
# copy packages
install -d -p %{buildroot}/%{gopath}/src/%{goipath}/
for file in ./* ; do
    if [ -d $file ]; then
        cp -rpav $file %{buildroot}%{gopath}/src/%{goipath}/
    fi
done

%if %{with check}
export GOPATH=%{buildroot}/%{gopath}:%{gopath}

%if ! 0%{?gotest:1}
%global gotest go test
%endif

pushd %{buildroot}/%{gopath}/src/%{gohost}.%{gosuffix}/%{goorg}/%{goproject}
#Note(mmagr): unit test fail currently. Uncomment this in next build
#%gotest ./...
popd
%endif

%files
%{gopath}/src/%{goipath}

%changelog
* Wed Sep 02 2020 Martin Magr <mmagr@redhat.com> - 0-0.1.20200810git9a73d9
- Initial package
